src/components/web/InputBox.jsx
src/components/web/LabelWithInput.jsx
src/stories/InputBox.stories.jsx
src/stories/LabelWithInput.stories.jsx

> ex) #2 
>  웹 공통 컴포넌트 만들었습니다.

[publishing-01/style] web 공통 컴포넌트 완성

---

package.json
src/setupTests.js
vite.config.js
yarn.lock

ex) #9 
Vitest, RTL를 위한 세팅 완료하고 직접 테스트까지 해봤어요 ~

[feature-01/feat] Vitest & React Testing Library 사용을 위한 세팅 완료

---

.github/workflows/storybook.yml
package.json
yarn.lock

#18 
Chromatic연동 storybook자동배포

[feature-02/Chromatic] Chromatic연동 storybook자동배포

---

.github/workflows/storybook.yml

develop 브랜치 추가 
Chromatic 자동배포에 develop 추가
develop 에 머지 또는 푸시하면 자동 배포

init: Chromatic 자동배포 develop추가

---

package.json
src/stories/Footer.stories.jsx
src/stories/FreeBoard.stories.jsx
src/stories/Header.stories.jsx
yarn.lock

[publishing-08/style] 스토리북 오류 해결

---

src/components/web/Button.jsx
src/components/web/Footer.jsx
src/components/web/Header.jsx
src/components/web/InputBox.jsx
src/components/web/LabelWithInput.jsx
src/components/web/PwInputBox.jsx
src/domains/Find/common/components/FindLink.jsx
src/domains/Find/common/components/InputEmail.jsx
src/domains/Find/common/components/NewPasswordInput.jsx
src/domains/Find/common/components/OTPInput.jsx
src/domains/Find/common/components/PageBox.jsx
src/domains/Find/common/components/PageTitle.jsx
src/domains/Find/detail/ChangePwPage.jsx
src/domains/Find/detail/FindIDCompletePage.jsx
src/domains/Find/detail/FindPwCheckIDPage.jsx
src/domains/Find/detail/FindPwEnterID.jsx
src/domains/Find/main/FindIDPage.jsx
src/domains/Find/main/FindPwPage.jsx
src/domains/login/common/components/DomainSelector.jsx
src/domains/login/common/components/EmailInput.jsx
src/domains/login/common/components/IDInput.jsx
src/domains/login/common/components/JoinButton.jsx
src/domains/login/common/components/JoinForm.jsx
src/domains/login/common/components/LoginForm.jsx
src/domains/login/common/components/NicknameInput.jsx
src/domains/login/common/components/PasswordInput.jsx
src/domains/login/main/Join.jsx
src/routes/Layout.jsx
src/routes/RouterPath.js
src/routes/routes.jsx

[publishing-11/style] 아이디, 비밀번호 찾기

---

src/domains/my/detail/EditPassword.jsx
src/domains/my/detail/MyScrap.jsx
src/domains/my/detail/PasswordMis.jsx
src/domains/my/mypage/components/MyActivity.jsx
src/routes/RouterPath.js
src/routes/routes.jsx

[publishing-15/style] 비밀번호 수정,일치확인,불일치

---

src/domains/job/common/components/LastFormLine.jsx
src/domains/job/common/components/form/EmploymentType.jsx
src/domains/job/common/components/form/JobCategory.jsx
src/domains/job/common/components/form/PersonalInfo.jsx
src/domains/job/common/components/form/PostContent.jsx
src/domains/job/common/components/form/PostTitle.jsx
src/domains/job/common/utils/jobCategories.js
src/domains/job/recruitment/components/WriteRecruitmentPostingForm.jsx
src/domains/job/recruitment/components/form/ClosingDate.jsx
src/domains/job/recruitment/components/form/CompanyWebsite.jsx
src/domains/job/recruitment/components/form/WorkPlace.jsx
src/domains/job/recruitment/service/postService.js
src/domains/job/search/components/WriteJobSearchPostingForm.jsx
src/domains/job/search/components/form/ContactEmail.jsx
src/domains/job/search/components/form/WorkExperience.jsx
src/domains/job/search/service/postService.js
src/domains/job/service/postService.js

#50 
- 구인 글 작성 API 연동 완료
- 구직 글 작성 API 연동 완료 
- API 연동만 완료했고 확인은 못 했어요🥲

[feature-06/feat] 구인&구직 글 작성 API 연동 완료

---

src/App.jsx
src/components/web/InputBox.jsx
src/domains/Find/common/components/InputEmail.jsx
src/domains/Find/common/components/OTPInput.jsx
src/domains/Find/detail/FindPwCheckIDPage.jsx
src/domains/Find/detail/FindPwEnterID.jsx
src/domains/Find/services/useFindIDServices.js
src/domains/Find/services/useFindPWServices.js
src/hooks/login/useInputBox.test.js
src/store/find/useFindPWStore

[feature-10/feat] 비밀번호 찾기 

---

src/components/web/WorkBoard.jsx
src/domains/community/comment/components/CommentForm.jsx
src/domains/community/comment/components/CommentHeader.jsx
src/domains/community/comment/components/CommentList.jsx
src/domains/community/comment/hooks/useCommentActions.js
src/domains/community/comment/store/useCommentStore.js
src/domains/community/detail/page/DetailCommunityPage.jsx
src/domains/community/main/page/CommunityMainPage.jsx
src/domains/community/service/commentService.js
src/domains/community/service/postService.js
src/domains/community/write/page/WriteCommunityPostPage.jsx
src/domains/job/common/components/LastFormLine.jsx

[feature-13/feat] 자유게시판 댓글 완성

---

src/domains/login/page/KakaoRedirectHandler.jsx
src/domains/login/page/KakaoSuccess.jsx
src/domains/login/services/useLoginServices.js
src/routes/routes.jsx
src/services/api/axios.js

fix: 카카오 로그인 수정1

---

src/domains/login/page/NaverSuccess.jsx
src/routes/routes.jsx
src/services/api/axios.js

fix:네이버 로그인 수정1

---

lighthouserc.json
src/components/app/MobileFreeBoard.jsx
src/components/web/FreeBoard.jsx
src/domains/community/detail/page/UserPosts.jsx
src/domains/community/main/page/CommunityMainPage.jsx
src/domains/community/service/postService.js
src/domains/community/service/useSearchPosts.js
src/domains/job/main/service/jobMainService.js
src/routes/RouterPath.js
src/routes/routes.jsx

#130 
- 자유게시판 글 검색 수정 완료 
- 특정 사용자가 작성한 글 조회 페이지 완료
리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

[bug-07/fix] 자유게시판 글 검색 & 특정 사용자가 작성한 글 조회 수정 완료

---

src/domains/login/page/NaverSuccess.jsx
src/services/api/axios.js
src/store/login/useAuthStore.js

[feature-30/feat] fix: 토큰 bearer수정

---

src/store/login/useAuthStore.js

[feature-30/feat] 로그인 연장 기능 수정3

[feature-30/feat] 로그인 연장 기능 수정3

---

src/domains/login/services/useLoginServices.js
src/store/login/useAuthStore.js

[release-v0.10] 10차 버스 출발

---

src/domains/login/services/useLoginServices.js
src/services/api/axios.js
src/store/login/useAuthStore.js

[release-v0.11] 11차 버스 출발 

---

src/services/api/axios.js

[feature-30/feat] 로그인 연장 기능 수정7

[feature-30/feat] 로그인 연장 기능 수정7

---

src/services/api/axios.js

[feature-30/feat] 로그인 연장 기능 수정8

[feature-30/feat] 로그인 연장 기능 수정8

---

src/services/api/axios.js
src/store/login/useAuthStore.js

[release-v0.13] 13차 버스 출발

---

src/services/api/axios.js
src/store/login/useAuthStore.js

[feature-30/feat] 로그인 연장 기능 수정10

[feature-30/feat] 로그인 연장 기능 수정10

---

src/services/api/axios.js
src/store/login/useAuthStore.js

[release-v0.15] 15차 버스 출발

---

src/services/api/axios.js
src/store/login/useAuthStore.js

[release-v0.16] 16차 버스 출발

---

src/stories/BgNoneButton.stories.jsx
src/stories/Button.stories.jsx

[release-v0.34] 34차 버스 출발

---

index.html
src/stories/BgNoneButton.stories.jsx

[release-v0.35] 35차 버스 출발

---

src/components/common/Banner.jsx
src/components/common/LikeCountReadOnly.jsx

[bug-30/fix] 좋아요 수정 & 리액트 캐러셀 삽입 완료
